default:
  image: "archlinux:latest"

stages:
  - test

release:
  stage: test
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - apk update
    - apk add jq curl httpie
  script:
    - export BUILD_VERSION=20211018.0.36946
    - |
      base_url=$(./ci/get-public-download-for-generic-package.sh base-${BUILD_VERSION}.tar.xz)
      echo "${base_url}"
      base_sha_url=$(./ci/get-public-download-for-generic-package.sh base-${BUILD_VERSION}.tar.xz.SHA256)
      echo "${base_sha_url}"
      base_devel_url=$(./ci/get-public-download-for-generic-package.sh base-devel-${BUILD_VERSION}.tar.xz)
      echo "${base_devel_url}"
      base_devel_sha_url=$(./ci/get-public-download-for-generic-package.sh base-devel-${BUILD_VERSION}.tar.xz.SHA256)
      echo "${base_devel_sha_url}"

      # TODO: We should actually be able to do something like \"url\":\"${PACKAGE_REGISTRY_URL}/base-${BUILD_VERSION}.tar.xz\"
      # But it doesn't appear that those downloads are public. I consider this a bug and hopefully it's fixed in a future version!
      echo "Getting release"
      release-cli --private-token "${GITLAB_PROJECT_TOKEN}" get \
      --tag-name v${BUILD_VERSION}
