default:
  image: "archlinux:latest"

stages:
  - test

release:
  stage: test
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - apk update
    - apk add jq curl httpie
  script:
    - export GITLAB_PROJECT_TOKEN=foobar
    - export BUILD_VERSION=20211017.0.36844
    - |
      echo "GITLAB_PROJECT_TOKEN: ${GITLAB_PROJECT_TOKEN}"
